### ISSUE TITLE
mm or cm in output graph

### ISSUE THREAD

**Issue by IRRICL** [shannonjryan/pyBLOSSUM#1]
Hello,

Was running the program and noticed that the output of the graph for the projectile diameter is in mm. Should this be in cm? Have put a sample run below. (I extended the velocity range to 40km/s)

![SampleRuncm](https://github.com/user-attachments/assets/08e76f6a-9dce-4790-af6e-fb0abc149a3b)

**Comment by shannonjryan** [comment]
You're correct, it should be in cm. I've pushed an update to correct the issue, thanks for reporting it.

**Comment by IRRICL** [comment]
No worries, and thank you for your program btw, very nice work!
